### ISSUE TITLE
Feature: Configurable buttons

### ISSUE THREAD

**Issue by greggheller** [corbennett/data-video-gui#5]
Include params in an array/json/csv so users can easily change the key strokes, and also possibly the label position? I liked having the visual layout match the physical layout of the buttons I chose

**Comment by corbennett** [comment]
Ok, Didn't see the position part until now. BUT, there is a 'shortcuts.json' file now that the user can use to specify the key shortcuts. Note that right now this file must be called 'shortcuts.json' and live in the same directory as the GUI.
