### ISSUE TITLE
Flip through annotations

### ISSUE THREAD

**Issue by taminar** [corbennett/data-video-gui#9]
Ability to flip through the frames for each category

**Comment by corbennett** [comment]
Just added this feature. On the top left of the panel you should see "Seek to" followed by a drop down menu. That will select the category to flip through. Then you can use the '<' and '>' buttons (without shift) to scroll through (these shortcuts are configurable and have been added to the shortcuts json file).

Note that when you select the drop down category, you have to click on the image window before attempting to scroll through the frames. I'll try to fix this in the future.
